{{- if .Values.BDDAWS }}
apiVersion: v1
data:
  AWS_SECRET_ACCESS_KEY: {{ .Values.BDDAWS.secret | b64enc | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.BDDAWS.id | b64enc | quote }}
kind: Secret
metadata:
  name: jx-bdd-aws
  annotations:
    jenkins.io/foo: bar
type: Opaque
{{- end }}