apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: infra-jrawlings-co-uk
spec:
  secretName: tls-infra-jrawlings-co-uk
  issuerRef:
    name: letsencrypt-prod
  commonName: '*.staging.jrawlings.co.uk'
  dnsNames:
  - '*.staging.jrawlings.co.uk'
  acme:
    config:
    - dns01:
        provider: prod-dns
      domains:
      - '*.staging.jrawlings.co.uk'