{{- if .Values.ExternalDNS }}
apiVersion: v1
data:
  credentials.json: {{ .Values.ExternalDNS.Data | b64enc | quote }}
kind: Secret
metadata:
  annotations:
    # Workaround until Kubernetes Credentials Provider can deal with a secret without annotations.
    jenkins.io/foo: bar
  labels:
    jenkins.io/credentials-type: secretText
  name: external-dns-secret
type: Opaque
{{- end }}
