{{- if .Values.JenkinsXGitHubTest }}
apiVersion: v1
data:
  password: {{ .Values.JenkinsXGitHubTest.password | b64enc | quote }}
  username: {{ .Values.JenkinsXGitHubTest.username | b64enc | quote }}
kind: Secret
metadata:
  name: jenkins-x-bot-test-github
  annotations:
    jenkins.io/credentials-description: API Token for acccessing https://github.com Git service for tests
  labels:
    jenkins.io/created-by: jx
    jenkins.io/credentials-type: usernamePassword
    jenkins.io/kind: git
    jenkins.io/service-kind: github
type: Opaque
{{- end }}