{{- if .Values.JenkinsXGHETestUser }}
apiVersion: v1
data:
  password: {{ .Values.JenkinsXGHETestUser.password | b64enc | quote }}
  username: {{ .Values.JenkinsXGHETestUser.username | b64enc | quote }}
kind: Secret
metadata:
  name: jx-pipeline-git-github-ghe
  annotations:
    jenkins.io/credentials-description: API Token for acccessing https://github.beescloud.com
      Git service inside pipelines
    jenkins.io/foo: bar
    jenkins.io/name: GHE
    jenkins.io/url: https://github.beescloud.com
  labels:
    jenkins.io/created-by: jx
    jenkins.io/credentials-type: usernamePassword
    jenkins.io/kind: git
    jenkins.io/service-kind: github
type: Opaque
{{- end }}