{{- if .Values.npmToken }}
apiVersion: v1
data:
  file: {{ "//registry.npmjs.org/:_authToken=" | b64enc }}{{.Values.npmToken  | b64enc }}
kind: Secret
metadata:
  name: npm-token
type: Opaque
{{- end }}